# Site settings
title: aiden_port-fol.io
description: Portfolio, showcase and perhaps blog for the guy in the url.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aiden Rutter
user_description: Software development and engineering with a passion for results. Into libre software, because I prefer to make my own upgrades and fixes. I think I'll add a description generator, or scrolling box?
user_title: Software Developer
email: me@arutter.net
# twitter_username: lorem_ipsum
github_username:  solsane
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-118332745-1"

exclude: ['package.json', 'src' , 'node_modules']
